version: '3.8'

services:
  domain-api:
    build: .
    container_name: domain-api
    restart: unless-stopped
    ports:
      - "3111:3111"
    environment:
      - NODE_ENV=production
      - VERCEL_TOKEN=${VERCEL_TOKEN}
    # opsional: batasi memori karena Bun sangat irit
    deploy:
      resources:
        limits:
          memory: 128M
